name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - run: docker login ghcr.io -u ${{ github.actor }} -p ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - run: ./gradlew assemble -Pstatic=true
      - run: ./gradlew build -Pstatic=true
      - run: docker build --platform linux/amd64 -t ghcr.io/hfhbd/kotlin-native-amd64 --build-arg nativeFolder=linuxX64 .
      - run: docker build --platform linux/arm64 -t ghcr.io/hfhbd/kotlin-native-arm64 --build-arg nativeFolder=linuxArm64 .
      - run: docker manifest create ghcr.io/hfhbd/kotlin-native -a ghcr.io/hfhbd/kotlin-native-amd64 -a ghcr.io/hfhbd/kotlin-native-arm64
      - run: docker manifest push ghcr.io/hfhbd/kotlin-native
